# localstack.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config
data:
  SERVICES: s3
  LOCALSTACK_HOSTNAME: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack
        envFrom:
        - configMapRef:
            name: localstack-config
        ports:
        - containerPort: 4566
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
  - port: 4566
    targetPort: 4566
