# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: album-app-service
spec:
  type: NodePort
  selector:
    app: album-app
  ports:
    - port: 80
      targetPort: 3001
      nodePort: 30080
